### PR TITLE
Remove null bytes in adapter name

### PR DESCRIPTION
**Pull request by easonchan1213**
Null chars in the input string will mislead us to target adapter. Simply delete all null chars should work.

### CODE REVIEW

**Comment by fcheung** [comment]
I have seen this before - it happens because the underlying driver is returning data encoded as UTF-16 (for which ascii characters have the high byte set to 0).

I thought I had fixed this here: https://github.com/dressipi/odbc_adapter/commit/25a9ddda8e6f203dc4b4d8b47d9739782643b7c2

I'd be very interested if you could stick a breakpoint in that file (line 45) & see how/why the conversion to utf8 is failing.

**Comment by easonchan1213** [comment]
Not sure why, it just doesn't work.
```
value = "R\x00\x00\x00e\x00\x00\x00d\x00\x00\x00s\x00\x00\x00h\x00\x00\x00i\x00\x00\x00f\x00\x00\x00t\x00\x00\x00".encode('ASCII-8BIT')
value.encoding
#<Encoding:ASCII-8BIT>

value.force_encoding('UTF-16LE').encode('UTF-8')
"R\u0000e\u0000d\u0000s\u0000h\u0000i\u0000f\u0000t\u0000"
```

**Comment by ghost** [comment]
Fannying around with encoding is a world of pain, much _much_ better to fix it at source if you can ...

**Comment by easonchan1213** [comment]
I believe so, couldn't figure out a way to fix that, had better to control the source.....

**Comment by fcheung** [comment]
Ah you've got 3 of them - UTF-32 rather than utf16.  this is controlled by a line in amazon.redshiftodbc.ini. On mac at least the version installed by default has

```
DriverManagerEncoding=UTF-32
```

which is what causes this

**Comment by ghost** [comment]
a world of pain, don't forget the byte-order-mark!

**Comment by easonchan1213** [comment]
You're right, it turns out to be `UTF-32`, not `UTF-16` on my machine. So the original `fix_encoding` works if the system setting is `UTF-16` but not others.

**Comment by easonchan1213** [comment]
It is a world of pain, I cannot change DriverManagerEncoding from UTF-32 to UTF-16/UTF-8 in `amazon.redshiftodbc.ini`, it seems it's still trying to do encoding conversion somewhere before it's fed to the adapter.

```
#<ODBC::Driver:0x00007f9d8127e900 @name="odbc", @attrs={"DRIVER"=>"{Amazon Redshift}", "SERVER"=>"localhost", "PORT"=>"5439", "DATABASE"=>"yisheng_development", "UID"=>"yisheng", "PWD"=>"XXXXX"}>

/Users/easonchan/git/odbc_adapter/lib/active_record/connection_adapters/odbc_adapter.rb:68:in `drvconnect': string contains null byte (ArgumentError)
	from /Users/easonchan/git/odbc_adapter/lib/active_record/connection_adapters/odbc_adapter.rb:68:in `odbc_conn_str_connection'
	from /Users/easonchan/git/odbc_adapter/lib/active_record/connection_adapters/odbc_adapter.rb:30:in `odbc_connection'
```

**Comment by fcheung** [comment]
Can't you just comment out that line in amazon.redshiftodbc.ini ?

**Comment by easonchan1213** [comment]
Yes, I can. But it defaults to `UTF-32`.....

**Pull request closed without merging**
